
# === FILE PATHS ===
# The root folder containing all your raw CS2 video captures.
# Use forward slashes (/) even on Windows.
captures_folder: "D:\\Captures\\Counter-strike 2"

# Folder to store intermediate data files (JSONs). Will be created if it doesn't exist.
data_folder: "./data"

# Folder to store the final, cut video clips. Will be created if it doesn't exist.
final_clips_folder: "./final_clips"


# === ANALYSIS PARAMETERS ===
# A list of your known in-game names. The system will use these for high-confidence kill attribution.
player_names:
  - "stingered by an WAS"
  - "marmalade sandwich"
  - "IZI KATKA"
  - "hot dog dog"
  - "excellent mage"
  - "pistol mage"

# Region of Interest (ROI) for the CS2 Killfeed (top-right of screen).
# You MUST find these coordinates yourself from a screenshot of your game.
# Format: [x1, y1, x2, y2] -> top-left corner (x1, y1) and bottom-right corner (x2, y2)
killfeed_roi: [2000, 40, 2530, 300] # Example for a 1920x1080 screen

# Region of Interest (ROI) for the Chat Box (bottom-left of screen).
chat_roi: [30, 1150, 650, 1300] # Example for a 1920x1080 screen

# HSV Color Range for the RED border around your kills.
# You may need to tweak this. Use an online tool to find the HSV values for your specific red.
# Red wraps around the 0-180 hue scale in OpenCV, so we need two ranges.
red_hsv_lower1: [0, 120, 70]
red_hsv_upper1: [10, 255, 255]
red_hsv_lower2: [170, 120, 70]
red_hsv_upper2: [180, 255, 255]

# The minimum number of red pixels to count as a valid kill border. Prevents noise.
min_red_contour_area: 200

# How many frames to skip during analysis. Higher is faster but less accurate.
ocr_frame_step: 30

# Whisper model to use. Options: tiny, base, small, medium, large.
whisper_model: "base"


# === CORRELATION & SCORING PARAMETERS ===
# The time window around a "trigger" event (like a kill) to look for other events.
clip_pre_buffer_seconds: 7
clip_post_buffer_seconds: 8

# Weights for scoring a potential clip. Tweak these to prioritize what you find important.
scoring_weights:
  kill: 10
  multi_kill_bonus: 15  # Additional points if 2+ kills are in the window
  team_hype_voice: 20   # Points for finding hype words in voice comms
  enemy_rage_chat: 25   # Points for finding negative sentiment in chat
  audio_spike: 5        # Points for a loud noise (shout/laughter)