# === FILE PATHS ===
# The root folder containing all your raw CS2 video captures.
# Use forward slashes (/) even on Windows.
# captures_folder: "D:\\Captures\\Counter-strike 2" # Windows
captures_folder: "/Users/nick/Desktop/Captures" # Mac

# Folder to store intermediate data files (JSONs). Will be created if it doesn't exist.
data_folder: "./data"

# Folder to store the final, cut video clips. Will be created if it doesn't exist.
final_clips_folder: "./final_clips"

# === ANALYSIS PARAMETERS ===
# A list of your known in-game names. The system will use these for high-confidence kill attribution.
player_names:
    - "stingered by an WAS"
    - "marmalade sandwich"
    - "IZI KATKA"
    - "hot dog dog"
    - "excellent mage"
    - "pistol mage"

# Region of Interest (ROI) for the CS2 Killfeed (top-right of screen).
# You MUST find these coordinates yourself from a screenshot of your game.
# Format: [x1, y1, x2, y2] -> top-left corner (x1, y1) and bottom-right corner (x2, y2)
killfeed_roi: [1920, 40, 2550, 300]

# Region of Interest (ROI) for the Chat Box (bottom-left of screen).
chat_roi: [30, 1150, 650, 1300]

# --- Kill Detection Tuning ---
red_hsv_lower1: [0, 120, 70]
red_hsv_upper1: [10, 255, 255]
red_hsv_lower2: [170, 120, 70]
red_hsv_upper2: [180, 255, 255]

# --- NEW: Color ranges for parsing names (T-side Orange, CT-side Blue) ---
# Tweak these using the tuner.py script!
t_orange_hsv_lower: [10, 150, 150]
t_orange_hsv_upper: [25, 255, 255]
ct_blue_hsv_lower: [100, 150, 150]
ct_blue_hsv_upper: [130, 255, 255]

# SHAPE DETECTION: Filters out red noise.
killfeed_rect_min_height: 25
killfeed_rect_max_height: 50
killfeed_rect_min_aspect_ratio: 8.0

# DEDUPLICATION: How long a kill is remembered after it disappears from the feed.
kill_memory_duration_seconds: 7.0

# --- General Analysis ---
ocr_frame_step: 30
whisper_model: "base"

# === CORRELATION & SCORING PARAMETERS ===
clip_pre_buffer_seconds: 7
clip_post_buffer_seconds: 8
scoring_weights:
    kill: 10
    multi_kill_bonus: 15
    team_hype_voice: 20
    enemy_rage_chat: 25
    audio_spike: 5
